services:
  sbomer-ui:
    build:
      context: ../
      dockerfile: ./images/sbomer-ui/Containerfile
    image: sbomer-ui:latest
    ports:
      - "8081:8080"
    environment:
      - API_URL=https://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
